Angular sidenav
SamirTouira/festival_charts pull request #4
Opened 2020-10-19 14:51 UTC by SamirTouira

Refactored some lines and integration of a responsive sidenav with Angular Material

2020-10-19 15:15 UTC, Mussuranae requested changes

2020-10-19 15:15 UTC, Mussuranae commented on src/app/add-movie/add-movie.component.html
> +  <h1 class="h2 custom-text">Add Movie</h1>
Pourquoi mettre une class `h2` sur un tag `h1` ? mets directement un `h2` si tu veux la typo des h2

2020-10-19 15:15 UTC, Mussuranae commented on src/app/add-movie/add-movie.component.html
> +  <mat-form-field appearance="outline" class="global-margin">
indentation cher ami, et la classe `global-margin` n'est plus utilisée, tu peux la supprimer

2020-10-19 15:15 UTC, Mussuranae commented on src/app/add-movie/add-movie.component.html
> +  <mat-form-field appearance="outline" color="primary" class="date-field">
la classe `date-fild` n'est plus utilisée non plus, tu peux supprimer aussi.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/add-movie/add-movie.component.html
> +  <mat-form-field appearance="outline" class="global-margin">
Il me semble que l'article et le mat-form-field doivent être à la même hauteur d'indentation ici, soit tu avances le mat-form-field, soit tu recules ton article. Supprime la class aussi.
Tu peux également sauter une ligne entre ton article et le mat-form-field pour y voir plus clair dans ton code

2020-10-19 15:15 UTC, Mussuranae commented on src/app/add-movie/add-movie.component.html
> +  <div class="form-group text-right">
Fais moi ce petit `text-right` avec le flex ;) si ton `form-group` n'est pas utile, tu peux supprimer.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/app.component.css
> +:host{
Teste, mais si rien ne fonctionne ou ne sert ici, tu peux supprimer tout le CSS.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/app.component.html
>  </style>
En vrai je pense que tu peux supprimer tout le CSS de base qu'ils ont mis dans le html et refaire un peu ton CSS dans les bons fichiers si besoin.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/edit-movie/edit-movie.component.html
>  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
Il y a trop de classe sur cette div, utilise le flexLayout !

2020-10-19 15:15 UTC, Mussuranae commented on src/app/edit-movie/edit-movie.component.html
>         <div class="btn-group">
Est-ce qu'elle sert encore vraiment ?

2020-10-19 15:15 UTC, Mussuranae commented on src/app/edit-movie/edit-movie.component.html
> +        <mat-form-field appearance="outline" class="global-margin">
Fais une petite recherche sur ton fihcier et enlève toutes les global-margin !

2020-10-19 15:15 UTC, Mussuranae commented on src/app/edit-movie/edit-movie.component.html
> +        <button type="submit" class="btn btn-success btn-block" [disabled]="!editForm.valid" (click)="edit()">
Utilise le bouton d'Angular Material ;)

2020-10-19 15:15 UTC, Mussuranae commented on src/app/movie-list/movie-list.component.html
> +        <button mat-raised-button color="accent" (click)="deleteMovie(movie)"><!--<i class="far fa-trash-alt"></i>--> Delete</button>
Tu peux supprimer ta petite icône en commetaire, ou alors transformer ce `raised-button` en `mat-icon-button` si tu veux garder ton icône.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/sidenav/material-module.ts
> +import {OverlayModule} from '@angular/cdk/overlay';
Bien tenté mais NON !!! Jamaissssss !!! Importe UNIQUEMENT ce dont tu as besoin, jamais plus !

2020-10-19 15:15 UTC, Mussuranae commented on src/app/sidenav/sidenav.component.html
> +    can be found in the LICENSE file at http://angular.io/license -->
Supprime ! Pas besoin de ce commentaire!.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/sidenav/sidenav.component.css
> +}
Je suis sûre que tu peux faire ton propre css ;)

2020-10-19 15:15 UTC, Mussuranae commented on src/app/sidenav/sidenav.component.ts
> +  shouldRun = [/(^|\.)plnkr\.co$/, /(^|\.)stackblitz\.io$/].some(h => h.test(window.location.host));
Pas utile, supprime.

2020-10-19 15:15 UTC, Mussuranae commented on src/app/sidenav/sidenav.component.ts
> +}
Inutile, on supprime !

2020-10-19 15:15 UTC, Mussuranae commented on src/styles.css
> +} */
Si pas utile, on supprime !

2020-10-20 14:06 UTC, Mussuranae approved these changes

2020-10-20 15:09 UTC, SamirTouira commented on src/app/edit-movie/edit-movie.component.html
>         <div class="btn-group">
Il me semble que oui, car quand je fais fxLayoutGap="15px", ça ne fonctionne pas :(

2020-10-21 08:05 UTC, merged